"""
The `offline_study` branch of robosuite did not unify controller poses across multiple robots.
So, we had to add upstream changes from this PR: https://github.com/ARISE-Initiative/robosuite/commit/fc3738ca6361db73376e4c9d8a09b0571167bb2d
We did this on our internal robosuite and bumped the version there, but we also need to postprocess
the old robomimic demos to make the relevant xml changes - that's what this script does.
"""


import h5py
import json
import argparse
import os
from shutil import copyfile
import robosuite
import xml.etree.ElementTree as ET


def change_robot(src_xml_str, dst_xml_str):
    """
    Change the robot in @dst_xml_str using the robot in @src_xml_str with
    some xml manipulation.
    """
    src_tree = ET.fromstring(src_xml_str)
    dst_tree = ET.fromstring(dst_xml_str)

    # (1) replace all meshes starting with robot0, mount0, gripper0 in destination with those in source

    # first delete the appropriate meshes in destination
    dst_asset = dst_tree.find("asset")
    dst_meshes = dst_asset.findall("mesh")
    for mesh in dst_meshes:
        mesh_name = mesh.get("name")
        if mesh_name is None:
            continue
        if (mesh_name is not None) and any([mesh_name.startswith(prefix) for prefix in ["robot0", "mount0", "gripper0"]]):
            dst_asset.remove(mesh)

    # then add the appropriate meshes from source
    src_asset = src_tree.find("asset")
    src_meshes = src_asset.findall("mesh")
    for mesh in src_meshes:
        mesh_name = mesh.get("name")
        if mesh_name is None:
            continue
        if (mesh_name is not None) and any([mesh_name.startswith(prefix) for prefix in ["robot0", "mount0", "gripper0"]]):
            dst_asset.append(mesh)

    # (2) replace body called robot0_base and everything underneath it from destination with the one from source
    dst_worldbody = dst_tree.find("worldbody")
    dst_robot_base = dst_worldbody.find("./body[@name='robot0_base']")
    ind = list(dst_worldbody).index(dst_robot_base)

    src_worldbody = src_tree.find("worldbody")
    src_robot_base = src_worldbody.find("./body[@name='robot0_base']")
    dst_worldbody[ind] = src_robot_base

    # (3) replace all actuators
    dst_actuator = dst_tree.find("actuator")
    ind = list(dst_tree).index(dst_actuator)

    src_actuator = src_tree.find("actuator")
    dst_tree[ind] = src_actuator

    return ET.tostring(dst_tree, encoding="utf8").decode("utf8")


def convert_xml(xml_str):
    """
    Postprocess xml string generated by robosuite to be compatible with upstream changes from this
    PR: https://github.com/ARISE-Initiative/robosuite/commit/fc3738ca6361db73376e4c9d8a09b0571167bb2d

    Args:
        xml_str (str): xml string to process (from robosuite v1.2)
    """

    def get_eef_panda_element(prefix):
        """
        Helper function for new element added in the unify EEF frames PR
        """

        eef_panda = """
        <body name="eef" pos="0 0 0.097" quat="1 0 0 0">
            <site name="grip_site" pos="0 0 0" size="0.01 0.01 0.01" rgba="1 0 0 0.5" type="sphere" group="1"/>
            <site name="ee_x" pos="0.1 0 0" size="0.005 .1"  quat="0.707105  0 0.707108 0 " rgba="1 0 0 0" type="cylinder" group="1"/>
            <site name="ee_y" pos="0 0.1 0" size="0.005 .1" quat="0.707105 0.707108 0 0" rgba="0 1 0 0" type="cylinder" group="1"/>
            <site name="ee_z" pos="0 0 0.1" size="0.005 .1" quat="1 0 0 0" rgba="0 0 1 0" type="cylinder" group="1"/>
            <!-- This site was added for visualization. -->
            <site name="grip_site_cylinder" pos="0 0 0" size="0.005 10" rgba="0 1 0 0.3" type="cylinder" group="1"/>
        </body>
        """

        tree = ET.ElementTree(ET.fromstring(eef_panda))
        root = tree.getroot()
        for elem in root.iter():
            elem.attrib["name"] = "{}_{}".format(prefix, elem.get("name"))

        return tree

    root = ET.fromstring(xml_str)
    worldbody = root.find('worldbody')
    bodies_to_process = []
    # remove elements that are specific to v1.2
    for body in worldbody.iter('body'):
        for site in body.findall('site'):
            site_name = site.get('name')

            # remove grip_site and grip_site_cylinder
            if 'grip_site' in site_name:
                # print("removing {site} from {body}".format(
                #     site=site_name,
                #     body=body.get('name'),
                # ))
                body.remove(site)
                if body not in bodies_to_process:
                    bodies_to_process.append(body)

            # remove site called robot{}_ee{}
            if site_name.startswith('robot') and 'ee' in site_name:
                # print("removing {site} from {body}".format(
                #     site=site_name,
                #     body=body.get('name'),
                # ))
                body.remove(site)

    # add elements introduced in the unify EEF frame PR
    for body in bodies_to_process:
        prefix = body.get("name").split('_')[0]
        eef_tree = get_eef_panda_element(prefix)
        body.append(eef_tree.getroot())

    # NOTE: important for robosuite with DM binding - get floorplane geom and add group="1"
    floor_geom = worldbody.find("./geom[@name='floor']")
    floor_geom.set("group", "1")

    xml_str = ET.tostring(root, encoding="utf8").decode("utf8")
    return xml_str

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--dataset",
        type=str,
        help="path to input hdf5 dataset",
    )
    parser.add_argument(
        "--output_dataset",
        type=str,
        help="path to output hdf5 dataset",
    )
    args = parser.parse_args()
    
    args.dataset = os.path.expanduser(args.dataset)
    args.output_dataset = os.path.expanduser(args.output_dataset)
    
    assert args.output_dataset != args.dataset
    assert robosuite.__version__ == '1.2.10'
    
    copyfile(args.dataset, args.output_dataset)
    
    f = h5py.File(args.output_dataset, "r+")

    for demo_key in list(f["data"].keys()):
        ep_data_grp = f["data/{}".format(demo_key)]
        model_file = ep_data_grp.attrs["model_file"]
        
        coverted_model_file = convert_xml(model_file)
        ep_data_grp.attrs["model_file"] = coverted_model_file
        
    env_args = json.loads(f["data"].attrs["env_args"])
    env_args["env_version"] = robosuite.__version__ 
    f["data"].attrs["env_args"] = json.dumps(env_args, indent=4)

    f.close()